Repository mercadopago/px-android, pull requests merged in 2022-04, with the labels that each got.

#2605 [Enhancement] Summary view header refactor
  CHANGELOG.md
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTap.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapFragment.java
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenter.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/view/ElementDescriptorView.java
  px-checkout/src/main/java/com/mercadopago/android/px/internal/view/HorizontalElementDescriptorView.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/view/SummaryHeaderCoordinator.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/view/SummaryView.java
  px-checkout/src/main/java/com/mercadopago/android/px/internal/view/VerticalElementDescriptorView.kt
  px-checkout/src/main/res/layout/px_view_express_summary.xml
  px-checkout/src/main/res/values/attrs.xml
  px-checkout/src/test/java/com/mercadopago/android/px/internal/features/one_tap/OneTapPresenterTest.kt
  px-checkout/src/test/java/com/mercadopago/android/px/internal/view/SummaryViewTest.kt
Labels: high priority, Refactor

#2696 [Fix]: PXN-3576 - Handler error when customOptionId is invalid
  CHANGELOG.md
  px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/OneTapItemRepositoryImpl.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/UserSelectionService.java
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/CongratsDeepLinkActivity.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/CongratsResult.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/CongratsViewModel.kt
  px-checkout/src/main/java/com/mercadopago/android/px/tracking/internal/events/FrictionEventTracker.kt
  px-checkout/src/test/java/com/mercadopago/android/px/internal/features/payment_congrats/CongratsViewModelTest.kt
Labels: bug, high priority, SEMOVI

#2700 Remove android id
  CHANGELOG.md
  px-addons/src/main/java/com/mercadopago/android/px/addons/ESCManagerBehaviour.java
Labels: Refactor
