Repository mercadopago/px-android, pull requests merged in 2022-03, with the labels that each got.

#2667 [FIX] Error screen when payment method not found
  gradle.properties
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonFragment.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonUiState.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonViewModel.kt
Labels: bug

#2672 [FIX] Duplicated payments
  CHANGELOG.md
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonFragment.kt
Labels: bug

#2682 [Fix]: PXN-3379 New method is added to keep session.
  CHANGELOG.md
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/CongratsDeepLinkActivity.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/payment_congrats/PaymentCongrats.kt
Labels: bug, SEMOVI

#2687 [Release] 4.108.1
  CHANGELOG.md
  gradle.properties
Labels: release

#2686 Fix/pxn 3384
  CHANGELOG.md
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/OneTapFragment.java
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/one_tap/offline_methods/OfflineMethodsFragment.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/features/pay_button/PayButtonFragment.kt
Labels: bug

#2690 [PXN-3415] getPaymentTypeId null
  CHANGELOG.md
  px-checkout/src/main/java/com/mercadopago/android/px/internal/datasource/PaymentMethodRepositoryImpl.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/mappers/PaymentMethodMapper.kt
  px-checkout/src/main/java/com/mercadopago/android/px/internal/repository/PaymentMethodRepository.kt
  px-checkout/src/test/java/com/mercadopago/android/px/internal/mapper/PaymentMethodMapperTest.kt
Labels: bug
